name: "Delete slot when the PR is closed"

on:
  pull_request:
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.WEB_APP_SP }}
    
    - name: Delete slot on staging site
      run: az webapp deployment slot delete --resource-group appserviceblogsite  --name antares-blog-staging --slot pr-${{ github.event.number }}
 
